CoreDemo/Areas/Admin/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreDemo.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CoreDemo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WriterController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult WriterList()
        {
            var jsonWriters = JsonConvert.SerializeObject(writers);
            return Json(jsonWriters);
        }

   
        public IActionResult GetWriterByID(int writerid)
        {
            var findWriter = writers.FirstOrDefault(x => x.Id == writerid);
            var jsonWriters = JsonConvert.SerializeObject(findWriter);
            return Json(jsonWriters);
        }

        [HttpPost]
        public IActionResult AddWriter(WriterClass w)
        {
            writers.Add(w);
            var jsonWriters = JsonConvert.SerializeObject(w);
            return Json(jsonWriters);

        }


        public IActionResult DeleteWriter(int id)
        {
            var writer = writers.FirstOrDefault(x => x.Id == id);
            writers.Remove(writer);
            return Json(writers);
        }

        public IActionResult UpdateWriter(WriterClass w)
        {
            var writer = writers.FirstOrDefault(x => x.Id == w.Id);
            writer.Name = w.Name;
            var jsonWriter = JsonConvert.SerializeObject(w);
            return Json(jsonWriter);
        }

        public static List<WriterClass> writers = new List<WriterClass>
       {
            new WriterClass
            {
                Id=1,
                Name="Ayşe"
            },
              new WriterClass
            {
                Id=2,
                Name="Ahmet"
            },
                new WriterClass
            {
                Id=3,
                Name="Buse"
            }
        };

    }
}

CoreDemo/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using CoreDemo.Models;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{
    public class WriterController : Controller
    {
        WriterManager wm = new WriterManager(new EFWriterRepository());
        private readonly UserManager<AppUser> _userManager;

        public WriterController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        [Authorize]
        public IActionResult Index()
        {
            var usermail = User.Identity.Name;
            ViewBag.v = usermail;
            Context c = new Context();
            var writerName = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterName).FirstOrDefault();
            ViewBag.v2 = writerName;
            return View();
        }

        public IActionResult WriterProfile() { return View(); }

        public IActionResult WriterMail() { return View(); }

        [AllowAnonymous]
        public IActionResult Test() { return View(); }

        [AllowAnonymous]
        public PartialViewResult WriterNavbarPartial()
        {
            return PartialView();
        }

        [AllowAnonymous]
        public PartialViewResult WriterFooterPartial()
        {
            return PartialView();
        }

        /*  [HttpGet]
          public async Task<IActionResult> WriterEditProfile()
          {
              Context c = new Context();
              var username = User.Identity.Name;
              var usermail = c.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
              UserManager userManager = new UserManager(new EFUserRepository());

              //   var writerID = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterID).FirstOrDefault();
              //   var writervalues = wm.TGetById(writerID);
              //   return View(writervalues); 

              var id = c.Users.Where(x => x.Email == usermail).Select(y => y.Id).FirstOrDefault();
              var values = userManager.TGetById(id);
              return View(values);
          }*/


        [HttpGet]
        public async Task<IActionResult> WriterEditProfile()
        {
            var values = await _userManager.FindByNameAsync(User.Identity.Name);
            UserUpdateViewModel model = new UserUpdateViewModel();
            model.mail = values.Email;
            model.namesurname = values.NameSurname;
            model.imageurl = values.ImageUrl;
            model.username = values.UserName;
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> WriterEditProfile(UserUpdateViewModel model)
        {
            var values = await _userManager.FindByNameAsync(User.Identity.Name);
          
            values.NameSurname = model.namesurname;
            values.ImageUrl = model.imageurl;
            model.mail = model.mail;
            values.PasswordHash = _userManager.PasswordHasher.HashPassword(values, model.password);
            var result = await _userManager.UpdateAsync(values);
            return RedirectToAction("Index", "Dashboard");
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult WriterAdd()
        {
            return View();
        }



        [AllowAnonymous]
        [HttpPost]
        public IActionResult WriterAdd(AddProfileImage p)
        {
            Writer w = new Writer();
            if (p.WriterImage != null)
            {
                var extension = Path.GetExtension(p.WriterImage.FileName);
                var newImageName = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/WriterImageFiles/", newImageName);
                var stream = new FileStream(location, FileMode.Create);
                p.WriterImage.CopyTo(stream);
                w.WriterImage = newImageName;
            }
            w.WriterMail = p.WriterMail;
            w.WriterName = p.WriterName;
            w.WriterPassword = p.WriterPassword;
            w.WriterStatus = true;
            w.WriterAbout = p.WriterAbout;
            wm.TAdd(w);
            return View();
        }



    }
}

CoreDemo/Views/Writer/Index.cshtml
@{
    Layout = null;
}

<h1>@ViewBag.v</h1>
<br />
<h3>Welcome, @ViewBag.v2</h3>

CoreDemo/Views/Writer/Test.cshtml
@{
    Layout = null;
     Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<h1>sjsjssj</h1>

CoreDemo/Views/Writer/WriterAdd.cshtml
@model CoreDemo.Models.AddProfileImage
@{
    ViewData["Title"] = "WriterAdd";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<form classclass="form-group" method="post" enctype="multipart/form-data">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Basic form elements</h4>
                <p class="card-description"> Edit Writer Profile Info </p>
                <br />
                @Html.HiddenFor(x=>x.WriterID, new {@class="form-control"})
                <div class="forms-sample">
                    <div class="form-group">
                        <label for="exampleInputName1">Name</label>
                        @Html.TextBoxFor(x=>x.WriterName, new {@class="form-control"})
                        @Html.ValidationMessageFor(x=>x.WriterName)

                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Email address</label>
                        @Html.TextBoxFor(x=>x.WriterMail, new {@class="form-control"})
                        @Html.ValidationMessageFor(x=>x.WriterMail)

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword4">Password</label>
                        @Html.PasswordFor(x=>x.WriterPassword, new {@class="form-control"})
                        @Html.ValidationMessageFor(x=>x.WriterPassword)

                    </div>

                    <div class="form-group">
                        <label>File upload</label>
                       <input type="file" name="WriterImage"/>
                    </div>

                    <div class="form-group">
                        <label for="exampleTextarea1">About Writer</label>
                        @Html.TextAreaFor(x=>x.WriterAbout,10,3, new {@class="form-control"})
                    </div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                </div>
            </div>
        </div>
    </div>

</form>

CoreDemo/Views/Writer/WriterEditProfile.cshtml
@model UserUpdateViewModel

@{
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

@using (Html.BeginForm("WriterEditProfile", "Writer", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Edit Writer Profile Info</h4>
                <p class="card-description">  </p>
                <br />

                <form class="forms-sample" method="post">

                    <div class="form-group">
                        <label for="exampleInputName1">Name Surname</label>
                        <input type="text" asp-for="@Model.namesurname" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="exampleInputName1">Username</label>
                        <input type="text" asp-for="@Model.username" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail3">Email address</label>
                        <input type="text" asp-for="@Model.mail" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail3">New Password</label>
                        <input type="text" asp-for="@Model.password" class="form-control" />
                    </div>


                    <div class="form-group">
                        <label for="exampleInputEmail3">Image</label>
                        <input type="text" asp-for="@Model.imageurl" class="form-control" />
                    </div>

                    <!--         <div class="form-group">
             <label for="exampleInputPassword4">Password</label>
         </div>
    -->
                    <!--       <div class="form-group">
           <label>File upload</label>
           <input type="file" name="img[]" class="file-upload-default">
           <div class="input-group col-xs-12">
               <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
               <span class="input-group-append">
                   <button class="file-upload-browse btn btn-gradient-primary" type="button">Upload</button>
               </span>
           </div>
       </div>

    -->
                    <!--   <div class="form-group">
        <label for="exampleTextarea1">About Writer</label>
       @* @Html.TextAreaFor(x=>x.WriterAbout,10,3, new {@class="form-control"})*@
    </div>-->
                    <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>

}

CoreDemo/Views/Writer/WriterFooterPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates </a> from Bootstrapdash.com</span>
    </div>
</footer>

CoreDemo/Views/Writer/WriterNavbarPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                  <!--  <img src="~/writer/assets/images/faces/face1.jpg" alt="profile">-->
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">Hoşgeldin</span>
                    <span class="text-secondary text-small"></span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Dashboard/Index/">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterEditProfile/">
                <span class="menu-title">My Profile</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogListByWriter/">
                <span class="menu-title">My Blogs</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogAdd/">
                <span class="menu-title">New Blog</span>
                <i class="mdi mdi-table-large menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Message/Inbox/">
                <span class="menu-title">Inbox</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Message/SendBox/">
                <span class="menu-title">Send Messages</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Notification/AllNotification/">
                <span class="menu-title">Notifications</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/Blog/Index/">
                <span class="menu-title">Go to Site</span>
                <i class="mdi mdi-car menu-icon"></i>
            </a>
        </li>
       
        <li class="nav-item">
            <a class="nav-link" href="/Login/LogOut/">
                <span class="menu-title">Log Out</span>
                <i class="mdi mdi-logout-variant menu-icon"></i>
            </a>
        </li>
    </ul>
</nav>

CoreDemo/Views/Writer/WriterProfile.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>WriterProfile</title>
</head>
<body>
</body>
</html>